#!/usr/bin/env python
# encoding: utf-8

name = "Seed"
shortDesc = u""
longDesc = u"""

"""
autoGenerated=True
entry(
    index = 0,
    label = "[CH2]CCCC + C[CH2] <=> n-heptane",
    degeneracy = 1.0,
    kinetics = Chebyshev(
        coeffs = [
            [12.6794, 0.334746, -0.0650807, -0.00485413],
            [-0.834771, 0.624245, -0.115723, -0.0110653],
            [-0.512951, 0.503497, -0.0784844, -0.0138722],
            [-0.341251, 0.345086, -0.0332269, -0.0154198],
            [-0.206239, 0.192637, 0.00444714, -0.0138394],
            [-0.105927, 0.0785052, 0.0251269, -0.00957977],
        ],
        kunits = 'cm^3/(mol*s)',
        Tmin = (300, 'K'),
        Tmax = (3000, 'K'),
        Pmin = (0.001, 'bar'),
        Pmax = (100, 'bar'),
    ),
)

entry(
    index = 1,
    label = "[CH2]CC + [CH2]CCC <=> n-heptane",
    degeneracy = 1.0,
    kinetics = Chebyshev(
        coeffs = [
            [12.6876, 0.329742, -0.0666834, -0.00486988],
            [-0.818095, 0.613481, -0.118542, -0.0111615],
            [-0.495679, 0.491235, -0.0805031, -0.0140599],
            [-0.324216, 0.332216, -0.034759, -0.0155322],
            [-0.191049, 0.181168, 0.00269881, -0.0136447],
            [-0.0941005, 0.0701749, 0.022801, -0.00901167],
        ],
        kunits = 'cm^3/(mol*s)',
        Tmin = (300, 'K'),
        Tmax = (3000, 'K'),
        Pmin = (0.001, 'bar'),
        Pmax = (100, 'bar'),
    ),
)

entry(
    index = 2,
    label = "[CH2]CC + C=C <=> [CH2]CCCC",
    degeneracy = 1.0,
    kinetics = Chebyshev(
        coeffs = [
            [7.85863, 0.659208, -0.111075, -0.00538984],
            [1.74986, 1.07175, -0.138014, -0.0230552],
            [-0.33094, 0.560335, 0.011403, -0.0318535],
            [-0.183732, 0.157422, 0.0837324, -0.0143256],
            [-0.0733543, -0.00340313, 0.0666536, 0.00902683],
            [-0.0412829, -0.0162751, 0.0277111, 0.0156223],
        ],
        kunits = 'cm^3/(mol*s)',
        Tmin = (300, 'K'),
        Tmax = (3000, 'K'),
        Pmin = (0.001, 'bar'),
        Pmax = (100, 'bar'),
    ),
)

entry(
    index = 3,
    label = "C[CH2] + C=C <=> [CH2]CCC",
    degeneracy = 1.0,
    kinetics = Chebyshev(
        coeffs = [
            [7.80035, 0.703483, -0.111795, -0.00406301],
            [1.6666, 1.11778, -0.125937, -0.0243252],
            [-0.35907, 0.54721, 0.0301732, -0.0316564],
            [-0.180173, 0.126137, 0.0888182, -0.00829409],
            [-0.0620818, -0.0255138, 0.0590128, 0.0148081],
            [-0.0327347, -0.0260898, 0.0184143, 0.0166701],
        ],
        kunits = 'cm^3/(mol*s)',
        Tmin = (300, 'K'),
        Tmax = (3000, 'K'),
        Pmin = (0.001, 'bar'),
        Pmax = (100, 'bar'),
    ),
)

entry(
    index = 4,
    label = "[CH3] + C=C <=> [CH2]CC",
    degeneracy = 1.0,
    kinetics = Chebyshev(
        coeffs = [
            [8.40331, 0.8283, -0.125453, 0.00402238],
            [1.68239, 1.16922, -0.0803278, -0.031173],
            [-0.358405, 0.449161, 0.0709417, -0.0257819],
            [-0.122318, 0.0526696, 0.0683458, 0.00618343],
            [-3.20631e-05, -0.0492101, 0.0197736, 0.0145238],
            [0.0233187, -0.0344255, -0.00446373, 0.00593872],
        ],
        kunits = 'cm^3/(mol*s)',
        Tmin = (300, 'K'),
        Tmax = (3000, 'K'),
        Pmin = (0.001, 'bar'),
        Pmax = (100, 'bar'),
    ),
)

entry(
    index = 5,
    label = "H + C=C <=> C[CH2]",
    degeneracy = 1.0,
    kinetics = Chebyshev(
        coeffs = [
            [12.0106, 0.891565, -0.165607, 0.0171206],
            [-0.182819, 1.00813, -0.0261492, -0.0384563],
            [-0.460149, 0.365116, 0.0688091, -0.0136191],
            [-0.206139, 0.0744013, 0.0421323, 0.0067531],
            [-0.0563281, -0.0126825, 0.00946828, 0.00652132],
            [0.00510678, -0.0211656, -0.0038628, 0.00157126],
        ],
        kunits = 'cm^3/(mol*s)',
        Tmin = (300, 'K'),
        Tmax = (3000, 'K'),
        Pmin = (0.001, 'bar'),
        Pmax = (100, 'bar'),
    ),
)

entry(
    index = 6,
    label = "C[CH2] + H <=> H2 + C=C",
    degeneracy = 3.0,
    kinetics = Arrhenius(
        A = (1.083e+13, 'cm^3/(mol*s)', '*|/', 2),
        n = 0,
        Ea = (0, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (300, 'K'),
        Tmax = (2500, 'K'),
        comment = 'Matched reaction 4 H + C2H5 <=> H2 + C2H4 in Disproportionation/training\nThis reaction matched rate rule [H_rad;Cmethyl_Csrad]\nfamily: Disproportionation',
    ),
    longDesc = 
u"""
Matched reaction 4 H + C2H5 <=> H2 + C2H4 in Disproportionation/training
This reaction matched rate rule [H_rad;Cmethyl_Csrad]
family: Disproportionation
""",
)

entry(
    index = 7,
    label = "H + H <=> H2",
    degeneracy = 1.0,
    kinetics = Chebyshev(
        coeffs = [
            [8.44324, 1.75223, -0.229696, -0.0184659],
            [0.0404948, 0.255013, 0.0765016, -0.0210795],
            [-0.109633, 0.049539, 0.00177192, -0.00209138],
            [-0.0408881, 0.0125475, 0.00190718, 0.00216847],
            [-0.0160913, 0.00396832, 0.0015907, 0.00139328],
            [-0.006217, 0.00146537, 0.000702537, 0.000605902],
        ],
        kunits = 'cm^3/(mol*s)',
        Tmin = (300, 'K'),
        Tmax = (3000, 'K'),
        Pmin = (0.001, 'bar'),
        Pmax = (100, 'bar'),
    ),
)

entry(
    index = 8,
    label = "[CH3] + [CH3] <=> C[CH2] + H",
    degeneracy = 1.0,
    kinetics = Chebyshev(
        coeffs = [
            [7.77653, -1.02965, -0.30715, 0.0124353],
            [4.43166, 0.907393, 0.170854, -0.0728572],
            [0.234208, 0.192798, 0.131158, 0.0248531],
            [0.0583593, -0.0115984, 0.0303438, 0.0301213],
            [0.00387239, -0.0413074, -0.0112709, 0.00997644],
            [-0.00264891, -0.0259081, -0.0154939, -0.00264457],
        ],
        kunits = 'cm^3/(mol*s)',
        Tmin = (300, 'K'),
        Tmax = (3000, 'K'),
        Pmin = (0.001, 'bar'),
        Pmax = (100, 'bar'),
    ),
)

entry(
    index = 9,
    label = "C[CH2] + [CH]=C <=> C=C + C=C",
    degeneracy = 3.0,
    kinetics = Arrhenius(
        A = (4.56e+14, 'cm^3/(mol*s)', '*|/', 1.5),
        n = -0.7,
        Ea = (0, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (300, 'K'),
        Tmax = (2500, 'K'),
        comment = 'Matched reaction 11 C2H3-2 + C2H5 <=> C2H4-2 + C2H4 in Disproportionation/training\nThis reaction matched rate rule [Cd_pri_rad;Cmethyl_Csrad]\nfamily: Disproportionation',
    ),
    longDesc = 
u"""
Matched reaction 11 C2H3-2 + C2H5 <=> C2H4-2 + C2H4 in Disproportionation/training
This reaction matched rate rule [Cd_pri_rad;Cmethyl_Csrad]
family: Disproportionation
""",
)

entry(
    index = 10,
    label = "H + [CH]=C <=> C=C",
    degeneracy = 1.0,
    kinetics = Chebyshev(
        coeffs = [
            [13.3083, 0.804432, -0.187488, 0.0247704],
            [-0.973874, 0.774703, -0.0208479, -0.0347103],
            [-0.538785, 0.298971, 0.0497137, -0.0123089],
            [-0.286123, 0.104622, 0.0300766, 0.00305858],
            [-0.145376, 0.030777, 0.011702, 0.00383292],
            [-0.0709463, 0.0068068, 0.00315339, 0.00161289],
        ],
        kunits = 'cm^3/(mol*s)',
        Tmin = (300, 'K'),
        Tmax = (3000, 'K'),
        Pmin = (0.001, 'bar'),
        Pmax = (100, 'bar'),
    ),
)

entry(
    index = 11,
    label = "H + C=C <=> H2 + [CH]=C",
    degeneracy = 4.0,
    kinetics = Arrhenius(
        A = (240, 'cm^3/(mol*s)'),
        n = 3.62,
        Ea = (11266, 'cal/mol'),
        T0 = (1, 'K'),
        comment = 'Matched reaction 217 C2H4 + H <=> C2H3_p + H2_p in H_Abstraction/training\nThis reaction matched rate rule [Cd/H2/NonDeC;H_rad]\nfamily: H_Abstraction',
    ),
    longDesc = 
u"""
Matched reaction 217 C2H4 + H <=> C2H3_p + H2_p in H_Abstraction/training
This reaction matched rate rule [Cd/H2/NonDeC;H_rad]
family: H_Abstraction
""",
)

entry(
    index = 12,
    label = "H + [CH]=C <=> H2 + C#C",
    degeneracy = 2.0,
    kinetics = Arrhenius(
        A = (678.823, 'm^3/(mol*s)'),
        n = 1.5,
        Ea = (-3.72376, 'kJ/mol'),
        T0 = (1, 'K'),
        comment = 'Estimated using template [H_rad;Cds/H2_d_Rrad] for rate rule [H_rad;Cds/H2_d_Crad]\nEuclidian distance = 1.0\nMultiplied by reaction path degeneracy 2.0\nfamily: Disproportionation',
    ),
    longDesc = 
u"""
Estimated using template [H_rad;Cds/H2_d_Rrad] for rate rule [H_rad;Cds/H2_d_Crad]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Disproportionation
""",
)

entry(
    index = 13,
    label = "[CH]=C + [CH]=C <=> C#C + C=C",
    degeneracy = 2.0,
    kinetics = Arrhenius(
        A = (8.20464, 'm^3/(mol*s)'),
        n = 1.87713,
        Ea = (-4.66621, 'kJ/mol'),
        T0 = (1, 'K'),
        comment = 'Estimated using template [Y_rad;Cds/H2_d_Rrad] for rate rule [Cd_pri_rad;Cds/H2_d_Crad]\nEuclidian distance = 2.2360679775\nMultiplied by reaction path degeneracy 2.0\nfamily: Disproportionation',
    ),
    longDesc = 
u"""
Estimated using template [Y_rad;Cds/H2_d_Rrad] for rate rule [Cd_pri_rad;Cds/H2_d_Crad]
Euclidian distance = 2.2360679775
Multiplied by reaction path degeneracy 2.0
family: Disproportionation
""",
)

entry(
    index = 14,
    label = "H + C#C <=> [CH]=C",
    degeneracy = 1.0,
    kinetics = Chebyshev(
        coeffs = [
            [11.4125, 1.25789, -0.20035, 0.00573766],
            [-0.114451, 0.900825, 0.0748409, -0.0305586],
            [-0.477011, 0.188116, 0.0668534, 0.00750951],
            [-0.195075, 0.0199911, 0.0134122, 0.00648707],
            [-0.0606016, -0.00702023, -0.00106949, 0.0007657],
            [-0.00660776, -0.00838662, -0.00139189, -0.000533885],
        ],
        kunits = 'cm^3/(mol*s)',
        Tmin = (300, 'K'),
        Tmax = (3000, 'K'),
        Pmin = (0.001, 'bar'),
        Pmax = (100, 'bar'),
    ),
)

entry(
    index = 15,
    label = "[CH3] + [CH]=C <=> C[C]C",
    degeneracy = 1.0,
    kinetics = Chebyshev(
        coeffs = [
            [13.1059, -0.795513, -0.304824, -0.0173715],
            [0.636937, 0.739171, 0.232452, -0.0272429],
            [0.110094, 0.151089, 0.100881, 0.0330977],
            [-0.0271784, -0.0320691, 0.00657427, 0.0203392],
            [-0.0329557, -0.0465254, -0.0202097, 0.000487281],
            [-0.0146196, -0.0224537, -0.0153807, -0.00644185],
        ],
        kunits = 'cm^3/(mol*s)',
        Tmin = (300, 'K'),
        Tmax = (3000, 'K'),
        Pmin = (0.001, 'bar'),
        Pmax = (100, 'bar'),
    ),
)

entry(
    index = 16,
    label = "C[CH2] + [CH3] <=> CH4 + C=C",
    degeneracy = 3.0,
    kinetics = Arrhenius(
        A = (6.57e+14, 'cm^3/(mol*s)', '*|/', 1.1),
        n = -0.68,
        Ea = (0, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (300, 'K'),
        Tmax = (2500, 'K'),
        comment = 'Matched reaction 5 CH3 + C2H5 <=> CH4 + C2H4 in Disproportionation/training\nThis reaction matched rate rule [C_methyl;Cmethyl_Csrad]\nfamily: Disproportionation',
    ),
    longDesc = 
u"""
Matched reaction 5 CH3 + C2H5 <=> CH4 + C2H4 in Disproportionation/training
This reaction matched rate rule [C_methyl;Cmethyl_Csrad]
family: Disproportionation
""",
)

entry(
    index = 17,
    label = "[CH]=C + CH4 <=> [CH3] + C=C",
    degeneracy = 4.0,
    kinetics = Arrhenius(
        A = (0.02236, 'cm^3/(mol*s)'),
        n = 4.34,
        Ea = (23.8488, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (300, 'K'),
        Tmax = (1500, 'K'),
        comment = 'Matched reaction 843 C2H3 + CH4b <=> C2H4 + CH3_p23 in H_Abstraction/training\nThis reaction matched rate rule [Cd/H2/NonDeC;C_methyl]\nfamily: H_Abstraction',
    ),
    longDesc = 
u"""
Matched reaction 843 C2H3 + CH4b <=> C2H4 + CH3_p23 in H_Abstraction/training
This reaction matched rate rule [Cd/H2/NonDeC;C_methyl]
family: H_Abstraction
""",
)

entry(
    index = 18,
    label = "H + [CH3] <=> CH4",
    degeneracy = 1.0,
    kinetics = Chebyshev(
        coeffs = [
            [12.8292, 1.38672, -0.25717, -0.0043861],
            [-0.988306, 0.645907, 0.0902281, -0.0302331],
            [-0.476838, 0.152143, 0.0527778, 0.00895987],
            [-0.225594, 0.038252, 0.017319, 0.00539208],
            [-0.106572, 0.00890648, 0.00444869, 0.00159387],
            [-0.0493721, 0.00149385, 0.0008858, 0.000325695],
        ],
        kunits = 'cm^3/(mol*s)',
        Tmin = (300, 'K'),
        Tmax = (3000, 'K'),
        Pmin = (0.001, 'bar'),
        Pmax = (100, 'bar'),
    ),
)

entry(
    index = 19,
    label = "H + CH4 <=> [CH3] + H2",
    degeneracy = 4.0,
    kinetics = Arrhenius(
        A = (4100, 'cm^3/(mol*s)'),
        n = 3.156,
        Ea = (8755, 'cal/mol'),
        T0 = (1, 'K'),
        comment = 'Matched reaction 186 CH4b + H <=> CH3_p1 + H2_p in H_Abstraction/training\nThis reaction matched rate rule [H2;C_methyl]\nfamily: H_Abstraction',
    ),
    longDesc = 
u"""
Matched reaction 186 CH4b + H <=> CH3_p1 + H2_p in H_Abstraction/training
This reaction matched rate rule [H2;C_methyl]
family: H_Abstraction
""",
)

entry(
    index = 20,
    label = "[CH3] + [CH]=C <=> CH4 + C#C",
    degeneracy = 2.0,
    kinetics = Arrhenius(
        A = (8.20464, 'm^3/(mol*s)'),
        n = 1.87713,
        Ea = (-4.66621, 'kJ/mol'),
        T0 = (1, 'K'),
        comment = 'Estimated using template [Y_rad;Cds/H2_d_Rrad] for rate rule [C_methyl;Cds/H2_d_Crad]\nEuclidian distance = 2.2360679775\nMultiplied by reaction path degeneracy 2.0\nfamily: Disproportionation',
    ),
    longDesc = 
u"""
Estimated using template [Y_rad;Cds/H2_d_Rrad] for rate rule [C_methyl;Cds/H2_d_Crad]
Euclidian distance = 2.2360679775
Multiplied by reaction path degeneracy 2.0
family: Disproportionation
""",
)

